description: 'small MLP, noise_model_level: 0 DAVIS Calcium hidden 128 n_layers 8'
dataset: 'fly_N9_54_1'

simulation:
    connectivity_file: 'to be specified'
    adjacency_matrix: ''

    params: [[1.0,1.0,1.0,1.0]]

    n_neurons: 13741
    n_input_neurons: 1736
    n_neuron_types: 65
    n_edges: 434112
    n_frames: 90720
    delta_t: 0.02
    baseline_value: 0
    
    calcium_type: "leaky"
    calcium_activation: "tanh"
    calcium_tau: 0.100
    calcium_down_sample: 10

    visual_input_type: "DAVIS"

graph_model:
    signal_model_name: 'PDE_N9_A'
    prediction: 'first_derivative'

    input_size: 3
    n_layers: 3
    hidden_dim: 64
    output_size: 1

    input_size_update: 5
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2

    update_type: 'generic'
    lin_edge_positive: True


    latent_dim: 64
    latent_update_steps: 20
    stochastic_latent: True
    latent_init_std: 1.0 

    input_size_encoder: 13741      # set to n_neurons
    n_layers_encoder: 8
    hidden_dim_encoder: 128

    latent_n_layers_update: 8
    latent_hidden_dim_update: 128
    output_size_decoder: 13741

    n_layers_decoder: 8
    hidden_dim_decoder: 128
    


plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [ -2.5,2.5 ]
    ylim: [ -100,100 ]

training:
    n_epochs: 10
    n_runs: 1
    device: 'auto'

    recurrent_loop: 1
    batch_size: 16
    batch_ratio: 1

    sparsity: 'none'
    rotation_augmentation: False
    data_augmentation_loop: 25

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 1.0E-3

    learning_rate_encoder: 1.0E-6
    learning_rate_latent_update: 1.0E-6
    learning_rate_decoder: 1.0E-6

    measurement_noise_level: 0
    noise_model_level: 0
    coeff_edge_diff: 500
    coeff_update_u_diff: 0
    coeff_update_msg_diff: 0
    coeff_edge_norm: 1000.0

    coeff_edge_weight_L1: 1
    coeff_phi_weight_L1: 1
    coeff_phi_weight_L1_rate: 0.5

    coeff_edge_weight_L2: 0
    coeff_phi_weight_L2: 0.001

    coeff_W_L1: 5.0E-5
    coeff_W_L1_rate: 0.5
