description: 'RNN successor  batch 32   noise_model_level: 1.0e-4 learning_rate_embedding_start: 1.0E-16 coeff_W_L1: 1.0E-4'
dataset: 'signal_N11_4_11'

simulation:
    connectivity_type: 'successor'
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Gaussian'
    params: [[7.0,1.0],[1.0,1.0],[1.0,1.0],[1.0,1.0]]
    phi: 'tanh'
    tau: 1.0
    n_neurons: 100
    n_neuron_types: 1
    n_frames: 10000
    delta_t: 0.1
    boundary: 'no'
    start_frame: -100

graph_model:
    signal_model_name: 'PDE_N11'
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64

    aggr_type: 'add'
    embedding_dim: 2

plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-2,2]

training:
    n_epochs: 30
    n_runs: 2
    device: 'auto'

    recursive_loop: 1
    batch_size: 32
    small_init_batch_size: False

    seed: 24

    data_augmentation_loop: 50

    sparsity: 'none'

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 1.0E-16

    coeff_W_L1: 1.0E-4

    noise_model_level: 1.0e-4

