description: 'synaptic network random matrix   cluster embedding distance 0.2   1000 neurons 4 types phi neuron-neuron dependent lorentz std 0.03   coeff_edge_diff 500'
dataset: 'signal_N5_l2'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0,1.0],[10.0,2.0,1.0,2.0],[10.0,1.0,2.0,4.0],[10.0,2.0,2.0,8.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 1000
    n_neuron_types: 4
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000

graph_model:
    signal_model_name: 'PDE_N5'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 5
    output_size: 1
    hidden_dim: 64
    n_layers: 3
    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 40
    n_epochs_init: 10
    recursive_loop: 1
    batch_size: 1
    small_init_batch_size: False
    n_runs: 2

    sparsity: 'replace_embedding_function'
    rotation_augmentation: False
    data_augmentation_loop: 100
    cluster_method: 'distance_embedding'
    cluster_distance_threshold: 0.2
    fix_cluster_embedding: True
    device: 'auto'
    sparsity: 'replace_embedding'
    sparsity_freq: 4

    learning_rate_W_start: 1.0E-4
    learning_rate_start: 5.0E-5
    learning_rate_embedding_start: 5.0E-4

    coeff_edge_diff: 500
