# stimulus-only null model configuration (20-step)
# predicts neural activity from stimulus context alone (no encoder/decoder/latent space)

num_neurons: 13741
activation: ReLU

stimulus_encoder_params:
  num_input_dims: 1736
  num_hidden_layers: 3
  num_hidden_units: 64
  num_output_dims: 64
  use_input_skips: true

predictor_params:
  num_hidden_layers: 2
  num_hidden_units: 512
  l1_reg_loss: 0.0
  use_input_skips: true

training:
  time_units: 20
  acquisition_mode:
    mode: time_aligned
  evolve_multiple_steps: 1
  simulation_config: "fly_N9_62_1_youtube-vos_calcium"
  data_passes_per_epoch: 1
  epochs: 30
  save_best_checkpoint: true
  save_checkpoint_every_n_epochs: 0
  diagnostics_freq_epochs: 1
  batch_size: 256
  learning_rate: 0.00001
  optimizer: Adam
  train_step: train_step
  column_to_model: "VOLTAGE"
  use_tf32_matmul: true
  seed: 234
  loss_function: mse_loss
  grad_clip_max_norm: 0.0
  pretrain_stimulus_ae: true
  stimulus_ae:
    epochs: 10
    batch_size: 256
    learning_rate: 0.0001
    optimizer: Adam

  data_split:
    train_start: 5120
    train_end: 972800
    validation_start: 973056
    validation_end: 987648

cross_validation_configs:
  - simulation_config: "fly_N9_62_0_optical_flow_calcium"
    name: "optical_flow"
    data_split:
      train_start: 0
      train_end: 1
      validation_start: 5000
      validation_end: 15000
  - simulation_config: "fly_N9_62_0_davis_calcium"
    name: "davis_2016_2017"
    data_split:
      train_start: 0
      train_end: 1
      validation_start: 5000
      validation_end: 25000
