description: 'test modulation with permutation'
dataset: 'signal_N4_m15'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0,1.0],[10.0,2.0,1.0,2.0],[10.0,1.0,1.2,4.0],[10.0,2.0,1.2,8.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 1024
    n_nodes: 1024
    n_neuron_types: 4
    shuffle_particle_types: True
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000
    node_value_map: 'video_bisons_32.tif'

graph_model:
    field_type: 'modulation_permutation'
    signal_model_name: 'PDE_N4'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 32
    output_size_nnr: 1024
    omega: 30.0

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 20
    n_runs: 2
    device: 'auto'

    n_epochs_init: 5
    recursive_loop: 1
    batch_size: 10
    small_init_batch_size: True

    rotation_augmentation: False
    data_augmentation_loop: 50
    cluster_method: 'kmeans_auto_embedding'
    cluster_distance_threshold: 0.2
    fix_cluster_embedding: True

    sparsity: 'none'
    sparsity_freq: 4

    coeff_edge_diff: 100

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3
    learning_rate_modulation_start: 1.0E-4

    learning_rate_NNR: 1.0E-5

    noise_model_level: 1
